# ============================================================================
# Tool Configuration File
# ============================================================================
# This file allows you to configure tool behavior without modifying code.
# Enable/disable tools, set categories, and control which tools the agent uses.

# Global tool settings
global:
  auto_discover: true  # Automatically discover tools in tools/ directory
  cache_instances: true  # Cache tool instances for reuse
  enable_validation: true  # Validate tools on registration

# Tool categories (for organization)
categories:
  - name: email
    description: Email and communication tools
    priority: high

  - name: calendar
    description: Calendar and scheduling tools
    priority: high

  - name: cv
    description: CV processing and candidate management
    priority: high

  - name: communication
    description: Meetings and video conferencing
    priority: medium

  - name: utility
    description: General utility tools
    priority: low

  - name: database
    description: Database operations
    priority: medium

# Individual tool configurations
# Override default settings for specific tools
tools:
  # Email tools
  gmail:
    enabled: true
    category: email
    requires_auth: true
    tags: [email, communication, google]
    priority: high

  # Calendar tools
  calendar:
    enabled: true
    category: calendar
    requires_auth: true
    tags: [calendar, scheduling, google]
    priority: high

  # CV management tools
  cv_sheet_manager:
    enabled: true
    category: cv
    requires_auth: true
    tags: [cv, sheets, google, crud]
    priority: high

  process_cvs:
    enabled: true
    category: cv
    requires_auth: true
    tags: [cv, processing, drive]
    priority: high

  search_candidates:
    enabled: true
    category: cv
    requires_auth: true
    tags: [cv, search, candidates]
    priority: high

  search_create_sheet:
    enabled: true
    category: cv
    requires_auth: true
    tags: [cv, sheets, search]
    priority: high

  # Communication tools
  webex:
    enabled: true
    category: communication
    requires_auth: true
    tags: [webex, meetings, video]
    priority: medium

  # Utility tools
  datetime:
    enabled: true
    category: utility
    requires_auth: false
    tags: [datetime, utility, time]
    priority: low

# MCP Tools configuration
mcp_tools:
  enabled: true
  mode: "mcp"  # "mcp" or "direct"

  # MCP server settings
  servers:
    thinking:
      enabled: true
      mode: mcp
      command: npx
      args: [-y, "@modelcontextprotocol/server-sequential-thinking"]

# Tool execution settings
execution:
  timeout_seconds: 300  # Maximum execution time per tool
  max_retries: 3  # Retry failed tool calls
  retry_delay_seconds: 1  # Delay between retries

# Logging and monitoring
logging:
  log_tool_calls: true
  log_tool_results: true
  log_errors: true
  log_performance: true

# Feature flags
features:
  enable_tool_caching: true
  enable_parallel_execution: false
  enable_tool_chaining: true
  enable_error_recovery: true

# Development settings
development:
  debug_mode: false
  verbose_logging: false
  hot_reload: false  # Auto-reload tools on file changes
